### ISSUE TITLE
AttributeError: 'Requirement' object has no attribute 'project_name'

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#64]
Got an error while deploying a charm baseed on the docker layer. I think the version of pip needs to be updated to the latest. Here is the log error:

```
Collecting docker-compose
  Using cached docker-compose-1.8.0.tar.gz
Collecting cached-property<2,>=1.2.0 (from docker-compose)
  Using cached cached_property-1.3.0-py2.py3-none-any.whl
Collecting docopt<0.7,>=0.6.1 (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): PyYAML<4,>=3.10 in /usr/lib/python3/dist-packages (from 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1006, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 535, in 
    dist = get_provider(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 415, in 
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 695, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (requests 2.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests<2.8,>=2.6.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR (2) running ['/var/lib/juju/agents/unit-kubernetes-0/charm/exec.d/docker-compose/charm-pre-install']
STDOUT<<EOM
None
EOM
```

**Comment by chuckbutler** [comment]
Ok, pip and the constantly moving docker libs is causing a very big headache. this was prior dealt with but backed out in:

https://github.com/juju-solutions/layer-docker/pull/43 
as well as
https://github.com/juju-solutions/layer-docker/pull/41
