### ISSUE TITLE
systemctl does not exist on Trusty

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-docker#74]
The systemctl command does not work on Trusty and the docker code is calling that. We need some code that makes the correct system calls based on series.

```
2016-08-29 16:32:52 INFO juju-log Writing file /etc/default/docker root:root 444
2016-08-29 16:32:52 INFO juju-log Writing file /lib/systemd/system/docker.service root:root 444
2016-08-29 16:32:52 INFO install Traceback (most recent call last):
2016-08-29 16:32:52 INFO install   File "/var/lib/juju/agents/unit-docker-1/charm/hooks/install", line 19, in <module>
2016-08-29 16:32:52 INFO install     main()
2016-08-29 16:32:52 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-08-29 16:32:52 INFO install     bus.dispatch()
2016-08-29 16:32:52 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-08-29 16:32:52 INFO install     _invoke(other_handlers)
2016-08-29 16:32:52 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-08-29 16:32:52 INFO install     handler.invoke()
2016-08-29 16:32:52 INFO install   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-08-29 16:32:52 INFO install     self._action(*args)
2016-08-29 16:32:52 INFO install   File "/var/lib/juju/agents/unit-docker-1/charm/reactive/docker.py", line 67, in install
2016-08-29 16:32:52 INFO install     reload_system_daemons()
2016-08-29 16:32:52 INFO install   File "/var/lib/juju/agents/unit-docker-1/charm/reactive/docker.py", line 156, in reload_system_daemons
2016-08-29 16:32:52 INFO install     check_call(command)
2016-08-29 16:32:52 INFO install   File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
2016-08-29 16:32:52 INFO install     retcode = call(*popenargs, **kwargs)
2016-08-29 16:32:52 INFO install   File "/usr/lib/python3.4/subprocess.py", line 537, in call
2016-08-29 16:32:52 INFO install     with Popen(*popenargs, **kwargs) as p:
2016-08-29 16:32:52 INFO install   File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
2016-08-29 16:32:52 INFO install     restore_signals, start_new_session)
2016-08-29 16:32:52 INFO install   File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
2016-08-29 16:32:52 INFO install     raise child_exception_type(errno_num, err_msg)
2016-08-29 16:32:52 INFO install FileNotFoundError: [Errno 2] No such file or directory: 'systemctl'
```

**Comment by chuckbutler** [comment]
Closed in #73
